site_name: Freezeyt
# site_url: ...
repo_url: https://github.com/encukou/freezeyt
edit_uri: edit/main/docs/
# site_description:
nav:
  - 'Home': 'index.md'
  - 'Configuration': 'config.md'
  - 'Contributing': 'contrib.md'
not_in_nav:
  licence.md
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  navigation_depth: 3
  # highlightjs: false  # disables user_color_mode_toggle?!
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - codehilite
  - tables
  - attr_list
  - markdown_include.include:
      base_path: docs
extra_css:
  - css/pygments.css
