site_name: Freezeyt
# site_url: ...
repo_url: https://github.com/encukou/freezeyt
edit_uri: edit/main/docs/
# site_description:
nav:
  - 'index.md'
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  # highlightjs: false  # disables user_color_mode_toggle?!
markdown_extensions:
  - toc:
      permalink: true
  - codehilite
extra_css:
  - css/pygments.css
