[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]

check_untyped_defs = true
disallow_incomplete_defs = true
warn_redundant_casts = true
warn_return_any = true
exclude = "tests/fixtures/"

# We use an ignore to support Python 3.10;
# so we can't turn this on yet:
# warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "cssutils"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "enlighten"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "falcon"
ignore_missing_imports = true
