# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

name: Freezeyt blog

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-blog-pages:
    # Name the Job
    name: Build blog static pages
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: |
              setup.cfg
              pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install .[blog]

      - name: Freeze blog app
        run: |
          python -m freezeyt freezeyt_blog.app freezeyt_blog/build -c freezeyt_blog/config.yaml

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # The branch the action should deploy to.
          folder: freezeyt_blog/build  # The folder the action should deploy.
          clean: true  # Automatically remove deleted files from the deploy branch
