on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: Main tests

jobs:
  tox_test:
    name: Tox env
    steps:
    - uses: actions/checkout@v3
    - name: Run Tox test
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [py36, py37, py38, py39, py310, py311, pyflakes, mypy310, mypy311]

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
