on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Main tests

jobs:
  fedora_tox_test:
    name: Tox env
    steps:
    - uses: actions/checkout@v6
    - name: Run Tox test
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [py39, py310, py311, py312, py313, py314, pyflakes, mypy310, mypy313]

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest

  uv_tox_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - python-version: '3.8'
          toxenv: 'py38'
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install tox
        run: |
          uv tool install --python ${{ matrix.python-version }} tox
      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}
